server:
  port: 9185
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:9186}/admin
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:11}
        instance:
          service-base-url: http://${AUTH_SERVICE_HOST:localhost}:${server.port}
          metadata:
            tags:
              environment: prd
  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}  # 指定了Zipkin服务器的地址

security:
  oauth2:
    client:
      client-id: web_app
      client-secret: $2a$10$S84wOzmAw4wqYBzAqNtmPOx1ZRWdDl9omm/W8T1hhW8S9EK2u57xG
      access-token-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/authorize
      grant-type: password
      scope: read
    resource:
      user-info-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/user/v1/user/info
      prefer-token-info: false
      jwt:
        key-uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9180}/api/auth/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjxSawA+NUNmhB2ctiVnt
          YH41WCNoD5STW2iPm5AIsKvm6X67lr6A88qOMRwx9oySdZnUnJ+8L3QJ51fkwuDe
          ix5w9yA3f/7LUPWZU8M/7Oi+2nda05JMgU999TUlhTGsp9SPiBqq/iwuqMxU8xKu
          F8bpTJTOpzrxH4e5BM6J/UJcOwDZLY6/3zP5w+tbhTvxjc995G4NtUyS4owE1MHe
          lj8IJepknjePrE6nXD6ecdL401hstMY838UOOFiCnM8NpiBuNI0nY0qCbb9mhQZ+
          7gP3jjM+Ft7R+MFTuEHWQ5UN8qHAPIT9UlLcu9IXdk6YwTsqNavwaTLUcP/ih9HB
          6wIDAQAB
          -----END PUBLIC KEY-----

# feign相关配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled:  true

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 短信配置
sms:
  appKey: ${SMS_APP_KEY:test}
  appSecret: ${SMS_APP_SECRET:test}
  regionId: ${SMS_REGION_ID:default}
  domain: ${SMS_DOMAIN:dysmsapi.aliyuncs.com}
  signName: ${SMS_SIGN_NAME:test}
  templateCode: ${SMS_TEMP_CODE:SMS_171192294}
  version: ${SMS_VERSION:2017-05-25}
  action: ${SMS_ACTION:SendSms}

ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /hystrix.sender
    - /v1/sms/**
    - /**/*.css
    - /**/*.js
    - /info
    - /health
    - /metrics/**
    - /loggers/**

# 集群ID生成配置
cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}
