version: '3'
services:
  # ---------------------------
  # api网关
  # ---------------------------
  gateway-service:
    image: registry.cn-hangzhou.aliyuncs.com/spring-microservice-exam/gateway-service:latest
    container_name: gateway-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9180:9180"
    volumes:
      - ./logs/gateway-service:/logs/gateway-service
    networks:
      - net

  # ---------------------------
  # 授权服务
  # ---------------------------
  auth-service:
    image: registry.cn-hangzhou.aliyuncs.com/spring-microservice-exam/auth-service:latest
    container_name: auth-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9182:9182"
    volumes:
      - ./logs/auth-service:/logs/auth-service
    networks:
      - net

  # ---------------------------
  # 用户服务
  # ---------------------------
  user-service:
    image: registry.cn-hangzhou.aliyuncs.com/spring-microservice-exam/user-service:latest
    container_name: user-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9183:9183"
    volumes:
      - ./logs/user-service:/logs/user-service
      - ./attach:/attach
    networks:
      - net

  # ---------------------------
  # 考试服务
  # ---------------------------
  exam-service:
    image: registry.cn-hangzhou.aliyuncs.com/spring-microservice-exam/exam-service:latest
    container_name: exam-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9184:9184"
    volumes:
      - ./logs/exam-service:/logs/exam-service
    networks:
      - net

  # ---------------------------
  # 消息服务
  # ---------------------------
  msc-service:
    image: registry.cn-hangzhou.aliyuncs.com/spring-microservice-exam/msc-service:latest
    container_name: msc-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9185:9185"
    volumes:
      - ./logs/msc-service:/logs/msc-service
    networks:
      - net

  # ---------------------------
  # 监控服务
  # ---------------------------
  monitor-service:
    image: registry.cn-hangzhou.aliyuncs.com/spring-microservice-exam/monitor-service:latest
    container_name: monitor-service
    env_file: docker-compose.env  # 从文件中获取配置
    restart: always
    ports:
      - "9186:9186"
    volumes:
      - ./logs/monitor-service:/logs/monitor-service
    networks:
      - net

networks:
  net:
    driver: bridge