# 生产环境的配置，采用git方式
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/wells2333/config-server      # 配置git仓库的地址
          username:                                                 # git仓库的账号
          password:                                                 # git仓库的密码
